// Явные переводы конкретных названий (идиоматичные, нестандартные).
// Ключ — название в нижнем регистре (сравнение после нормализации дефисов).
// Значение — строка (статус machine_draft) или объект { name, status?, notes? }.
export const OVERRIDES_PART1 = {
  // --- сильменские / стронг ---
  'atlas stones': 'Атласские камни (подъём)',
  'atlas stone trainer': 'Тренажёр для атласских камней',
  'axle deadlift': 'Становая тяга с осью (axle)',
  'car deadlift': 'Становая тяга автомобиля',
  'yoke walk': 'Переноска йока',
  "farmer's walk": 'Прогулка фермера',
  "conan's wheel": 'Колесо Конана',
  'crucifix': 'Распятие (удержание в стороны)',
  'keg load': 'Заброс бочки на помост',
  'sandbag load': 'Заброс мешка с песком',
  'log lift': 'Жим лога',
  'tire flip': 'Переворот шины',
  'power stairs': 'Силовые ступени (перенос снарядов)',
  'rickshaw carry': 'Переноска рикши',
  'rickshaw deadlift': 'Становая тяга в рикше',
  'battling ropes': 'Волны канатом (battling ropes)',
  'prowler sprint': 'Спринт с санями (prowler)',
  'sled push': 'Толкание саней',
  'bear crawl sled drags': 'Тяга саней ползанием по-медвежьи',
  'heavy bag thrust': 'Толчки тяжёлого мешка',
  'spell caster': 'Поворотные махи (spell caster)',
  'car drivers': '«Водитель» с диском (car drivers)',
  'sled overhead backward walk': 'Ходьба назад с санями над головой',
  'sled overhead triceps extension':
    'Разгибания рук с санями над головой (на трицепс)',
  'backward drag': 'Тяга саней спиной назад',
  'sled drag - harness': 'Тяга саней в упряжи',
  'sled row': 'Тяга в санях',
  'sled sprint': 'Спринт с санями',
  'backward medicine ball throw': 'Бросок медицинбола назад через голову',
  'two-arm overhead throw': 'Бросок над головой двумя руками',
  'supine two-arm overhead throw': 'Бросок над головой двумя руками лёжа',
  'supine one-arm overhead throw': 'Бросок над головой одной рукой лёжа',
  'supine chest throw': 'Бросок от груди лёжа',
  'catch and overhead throw': 'Ловля и бросок над головой',
  'one-arm medicine ball slam': 'Сброс медицинбола одной рукой',
  'overhead slam': 'Сброс мяча над головой (слэм)',
  'medicine ball chest pass': 'Пас медицинболом от груди',
  'medicine ball scoop throw': 'Бросок медицинбола снизу',
  'medicine ball full twist': 'Повороты с медицинболом',
};
export const OVERRIDES_PART2 = {
  // --- идиоматичные названия ---
  "world's greatest stretch": 'Величайшая растяжка мира',
  'around the worlds': '«Вокруг света» (разведения лёжа)',
  'london bridges': '«Лондонские мосты» (планка с шагами)',
  'kettlebell pirate ships': '«Пиратские корабли» с гирей (маятник)',
  'kettlebell pass between the legs': 'Передача гири между ног («восьмёрка»)',
  'kettlebell figure 8': '«Восьмёрка» с гирей',
  'kettlebell halo': '«Хало» с гирей (обводка вокруг головы)',
  'kettlebell halo with overhead extension':
    '«Хало» с гирей с разгибанием над головой',
  'kettlebell thruster': 'Трастер с гирей',
  'kettlebell seesaw press': 'Жим «качели» с двумя гирями',
  'kettlebell turkish get-up (lunge style)':
    'Турецкий подъём с гирей (вариант в выпаде)',
  'kettlebell turkish get-up (squat style)':
    'Турецкий подъём с гирей (вариант с приседанием)',
  'kettlebell windmill': 'Мельница с гирей',
  'advanced kettlebell windmill': 'Мельница с гирей (продвинутый вариант)',
  'double kettlebell windmill': 'Мельница с двумя гирями',
  'windmills': 'Мельницы',
  'bottoms-up clean from the hang position':
    'Взятие гири перевёрнутым хватом с виса',
  'bottoms up': 'Удержание гири дном вверх',
  'moving claw series': 'Серия «движущаяся лапа» (moving claw)',
  'frankenstein squat': 'Приседания «франкенштейн» (руки вперёд)',
  'gorilla chin/crunch': '«Горилла»: подтягивания с подъёмом коленей',
  'groiners': 'Прыжки в широкие выпады (groiners)',
  'inchworm': '«Гусеница» (inchworm)',
  'dead bug': '«Мёртвый жук» (dead bug)',
  'superman': '«Супермен» (разгибание спины лёжа)',
  'cocoons': '«Коконы» (скручивания с подтягиванием коленей)',
  'mountain climbers': '«Скалолазы» (бег в упоре лёжа)',
  'spell caster': 'Поворотные махи (spell caster)',
  'otis-up': 'Сит-ап с жимом гантелей (otis-up)',
  'press sit-up': 'Сит-ап с жимом',
  'janda sit-up': 'Сит-ап Янда',
  'butt-ups': 'Подъёмы таза в упоре (butt-ups)',
  'butt lift (bridge)': 'Подъём ягодиц (мост)',
  'pelvic tilt': 'Наклон таза (постериорный тилт)',
  'pelvic tilt into bridge': 'Наклон таза с переходом в мост',
  'physioball hip bridge': 'Ягодичный мост на фитболе',
  'isometric wipers': 'Изометрические «дворники»',
  'leg-over floor press': 'Жим гантелей с пола с забросом ноги',
  'body-up': 'Подъём корпуса из упора (body-up)',
  'body tricep press': 'Отжимания на трицепс собственным весом',
  'anti-gravity press': 'Жим «антигравитация» (piked)',
  'stomach vacuum': 'Вакуум живота',
  'svend press': 'Жим Свенда',
  'tate press': 'Жим Тейта',
  'jm press': 'Жим JM',
  'bent press': 'Жим в наклоне (bent press)',
  'pallof press': 'жим Паллофа',
  'pallof press with rotation': 'жим Паллофа с поворотом',
  'bent-arm barbell pullover': 'Пуловер со штангой согнутыми руками',
  'bent-arm dumbbell pullover': 'Пуловер с гантелью согнутыми руками',
  'straight-arm dumbbell pullover': 'Пуловер с гантелью прямыми руками',
  'front raise and pullover': 'Подъём перед собой и пуловер',
  'wide-grip decline barbell pullover':
    'Пуловер со штангой вниз головой широким хватом',
  'straight-arm pulldown': 'Тяга верхнего блока прямыми руками',
  'rope straight-arm pulldown': 'Тяга блока с канатом прямыми руками',
  'underhand cable pulldowns': 'Тяга верхнего блока обратным хватом',
  'full range-of-motion lat pulldown':
    'Тяга верхнего блока с полной амплитудой',
  'wide-grip pulldown behind the neck':
    'Тяга верхнего блока широким хватом из-за головы',
  'gironda sternum chins': 'Подтягивания Жиронды к грудине',
  'decline close-grip bench to skull crusher':
    'Комбо: жим узким хватом вниз головой + французский жим',
  'reverse triceps bench press': 'Жим обратным хватом на трицепс',
  'barbell curls lying against an incline':
    'Сгибания со штангой лёжа на наклонной скамье',
  'barbell rollout from bench': 'Выкатывание штанги от скамьи',
  'barbell ab rollout': 'Выкатывание штанги (аб-ролл)',
  'barbell ab rollout - on knees': 'Выкатывание штанги с колен (аб-ролл)',
  'ab roller': 'Ролик для пресса',
  'ab crunch machine': 'Тренажёр для скручиваний',
  'calf raise on a dumbbell': 'Подъём на носки, стоя на гантели',
  'donkey calf raises': 'Подъёмы на носки «ослик»',
  'rocking standing calf raise': 'Подъёмы на носки стоя с раскачкой',
  'wide stance stiff legs': 'Становая на прямых ногах, широкая постановка',
  'hanging bar good morning': 'Наклоны в висе на турнике (good morning)',
  'good morning off pins': 'Гуд морнинг со штырей в раме',
  'band good morning': 'Гуд морнинг с эспандером',
  'band good morning (pull through)':
    'Гуд морнинг с эспандером (тяга между ног)',
};
export const OVERRIDES_PART3 = {
  // --- гири ---
  'two-arm kettlebell clean': 'Взятие двух гирь',
  'two-arm kettlebell jerk': 'Толчок двух гирь',
  'two-arm kettlebell military press': 'Армейский жим двух гирь',
  'two-arm kettlebell row': 'Тяга двух гирь в наклоне',
  'double kettlebell jerk': 'Толчок двумя гирями',
  'double kettlebell push press': 'Швунг двумя гирями',
  'double kettlebell snatch': 'Рывок двумя гирями',
  'double kettlebell alternating hang clean':
    'Попеременное взятие двух гирь с виса',
  'one-arm kettlebell clean': 'Взятие гири одной рукой',
  'one-arm kettlebell clean and jerk': 'Толчок гири одной рукой (длинный цикл)',
  'one-arm kettlebell floor press': 'Жим гири с пола одной рукой',
  'one-arm kettlebell jerk': 'Толчок гири одной рукой',
  'one-arm kettlebell military press to the side':
    'Армейский жим гири в сторону одной рукой',
  'one-arm kettlebell para press': {
    name: 'Жим гири в стороне одной рукой (para press)',
    status: 'needs_review',
    notes: 'Термин «para press» неоднозначен — уточнить технику упражнения',
  },
  'one-arm kettlebell push press': 'Швунг гири одной рукой',
  'one-arm kettlebell row': 'Тяга гири в наклоне одной рукой',
  'one-arm kettlebell snatch': 'Рывок гири одной рукой',
  'one-arm kettlebell split jerk': 'Толчок гири в ножницы одной рукой',
  'one-arm kettlebell split snatch': 'Рывок гири в ножницы одной рукой',
  'one-arm kettlebell swings': 'Свинг гири одной рукой',
  'one-arm open palm kettlebell clean':
    'Взятие гири одной рукой открытой ладонью',
  'open palm kettlebell clean': 'Взятие гири открытой ладонью',
  'one-arm overhead kettlebell squats':
    'Приседания с гирей над головой одной рукой',
  'kettlebell dead clean': 'Взятие гири с пола',
  'kettlebell hang clean': 'Взятие гири с виса',
  'kettlebell one-legged deadlift': 'Становая тяга на одной ноге с гирей',
  'kettlebell overhead triceps extension':
    'Разгибание гири над головой на трицепс',
  'kettlebell seated press': 'Жим гири сидя',
  'kettlebell arnold press': 'Жим Арнольда с гирей',
  'kettlebell sumo high pull': 'Сумо-тяга гири к подбородку',
  'kettlebell pistol squat': 'Пистолетик с гирей',
  'alternating kettlebell press': 'Жим гири попеременно',
  'alternating kettlebell row': 'Тяга гири попеременно',
  'alternating hang clean': 'Взятие с виса попеременно',
  'alternating renegade row': 'Тяга ренегата попеременно',
  'renegade row': 'Тяга ренегата',
  'kettlebell swings': 'Свинг с гирей',

  // --- пресс / кор ---
  'kettlebell russian twist': 'Русские скручивания с гирей',
  'russian twist': 'Русские скручивания',
  'cable russian twists': 'Русские скручивания на блоке',
  'seated barbell twist': 'Повороты со штангой сидя',
  'plate twist': 'Повороты с диском',
  'cross-body crunch': 'Скручивания локоть-колено (крест-накрест)',
  'tuck crunch': 'Скручивания с подтянутыми коленями',
  'decline oblique crunch': 'Боковые скручивания на скамье вниз головой',
  'oblique crunches - on the floor': 'Боковые скручивания на полу',
  'crunch - hands overhead': 'Скручивания с руками над головой',
  'crunch - legs on exercise ball': 'Скручивания с ногами на фитболе',
  'exercise ball crunch': 'Скручивания на фитболе',
  'cable seated crunch': 'Скручивания на блоке сидя',
  'standing rope crunch': 'Скручивания на блоке с канатом стоя',
  'cable reverse crunch': 'Обратные скручивания на блоке',
  'decline reverse crunch': 'Обратные скручивания на скамье вниз головой',
  'kneeling cable crunch with alternating oblique twists':
    'Скручивания на блоке с колен с попеременными поворотами',
  'bosu ball cable crunch with side bends':
    'Скручивания на блоке на полусфере Босу с наклонами в сторону',
  'alternate heel touchers': 'Наклоны к пяткам (heel touchers)',
  'toe touchers': 'Касания носков',
  'standing toe touches': 'Наклоны к носкам стоя',
  'jackknife sit-up': 'Сит-ап складкой',
  'side jackknife': 'Боковая складка',
  'flat bench leg pull-in': 'Подтягивания коленей к груди на скамье',
  'seated leg tucks': 'Подтягивания коленей сидя',
  'knee across the body': 'Колено через корпус',
  'elbow to knee': 'Локоть к колену',
  'one knee to chest': 'Колено к груди',
  'knee/hip raise on parallel bars': 'Подъёмы коленей/таза на брусьях',
  'bent-knee hip raise': 'Подъёмы таза с согнутыми коленями',
  'flutter kicks': 'Махи ногами лёжа (ножницы)',
  'scissor kick': 'Ножницы',
  'scissors jump': 'Прыжки-ножницы',
  'single leg butt kick': 'Захлёст голени на одной ноге',
  'double leg butt kick': 'Прыжки с захлёстом голеней',
  'tuck jump': 'Прыжок с подтягиванием коленей',
  'rocket jump': 'Прыжок вверх (ракета)',
  'star jump': 'Прыжок «звёздочка»',
  'split jump': 'Прыжки со сменой ног (ножницы)',
  'stride jump crossover': 'Прыжки со сменой ног (кроссовер)',
  'standing long jump': 'Прыжок в длину с места',
  'side standing long jump': 'Прыжок в длину в сторону',
  'lateral bound': 'Многоскоки в сторону',
  'alternate leg diagonal bound': 'Диагональные многоскоки попеременно',
  'quick leap': 'Быстрый прыжок (многоскок)',
};
export const OVERRIDES_PART4 = {
  // --- растяжки / МФР / шея ---
  'neck-smr': 'Шея (МФР)',
  'neck press': 'Подъём головы с сопротивлением (шея)',
  'isometric neck exercise - front and back':
    'Изометрические упражнения для шеи — вперёд и назад',
  'isometric neck exercise - sides':
    'Изометрические упражнения для шеи — в стороны',
  'side neck stretch': 'Растяжка шеи в сторону',
  'looking at ceiling': 'Взгляд в потолок (растяжка шеи)',
  'chin to chest stretch': 'Подтягивание подбородка к груди',
  'lying face down plate neck resistance':
    'Подъём головы с диском лёжа на животе',
  'lying face up plate neck resistance':
    'Подъём головы с диском лёжа на спине',
  'seated head harness neck resistance':
    'Сопротивление для шеи с наголовной упряжью сидя',
  'side wrist pull': 'Тяга запястья в сторону (растяжка)',
  'wrist roller': 'Валик для запястий (wrist roller)',
  'wrist rotations with straight bar': 'Вращения запястий с прямым грифом',
  'finger curls': 'Сгибания пальцев',
  'plate pinch': 'Удержание диска пальцами (пинч)',
  'standing olympic plate hand squeeze': 'Сжатие диска ладонями стоя',
  'isometric chest squeezes': 'Изометрическое сжатие ладоней перед грудью',
  'one arm against wall': 'Одна рука у стены (растяжка груди)',
  'elbows back': 'Локти назад (растяжка груди)',
  'behind head chest stretch': 'Растяжка груди за головой',
  'chest and front of shoulder stretch': 'Растяжка груди и передних дельт',
  'chest stretch on stability ball': 'Растяжка груди на фитболе',
};
export const OVERRIDES_PART5 = {
  'child\'s pose': 'Поза ребёнка',
  'cat stretch': 'Растяжка «кошка»',
  'the straddle': 'Складка с широкими ногами (шпагат-растяжка)',
  'one half locust': 'Половинная «саранча»',
  'side bridge': 'Боковая планка',
  'plank': 'Планка',
  'push up to side plank': 'Отжимание с переходом в боковую планку',
  'suspended fallout': '«Падение» в петлях (fallout)',
  'hug a ball': 'Обнять мяч',
  'hug knees to chest': 'Колени к груди',
  'kneeling hip flexor': 'Растяжка сгибателей бедра на коленях',
  'standing hip flexors': 'Растяжка сгибателей бедра стоя',
  'intermediate hip flexor and quad stretch':
    'Растяжка сгибателей бедра и квадрицепсов (средний уровень)',
  'all fours quad stretch': 'Растяжка квадрицепсов на четвереньках',
  'on-your-back quad stretch': 'Растяжка квадрицепсов на спине',
  'on your side quad stretch': 'Растяжка квадрицепсов на боку',
  'standing elevated quad stretch': 'Растяжка квадрицепсов стоя с опорой',
  'lying prone quadriceps': 'Растяжка квадрицепсов лёжа на животе',
  'lying glute': 'Растяжка ягодиц лёжа',
  'seated glute': 'Растяжка ягодиц сидя',
  'it band and glute stretch': 'Растяжка ПБТ и ягодиц',
  'iliotibial tract-smr': 'Подвздошно-большеберцовый тракт (МФР)',
  'piriformis-smr': 'Грушевидная мышца (МФР)',
  'seated hamstring': 'Растяжка бицепса бедра сидя',
  'lying hamstring': 'Растяжка бицепса бедра лёжа',
  'prone manual hamstring': 'Сгибание ног с ручным сопротивлением лёжа',
  'seated floor hamstring stretch': 'Растяжка бицепса бедра сидя на полу',
  'seated hamstring and calf stretch': 'Растяжка бицепса бедра и икр сидя',
  'standing hamstring and calf stretch': 'Растяжка бицепса бедра и икр стоя',
  'leg-up hamstring stretch': 'Растяжка бицепса бедра с поднятой ногой',
  '90/90 hamstring': 'Растяжка бицепса бедра 90/90',
  'platform hamstring slides': 'Скольжения ногами (hamstring slides)',
  'lying bent leg groin': 'Растяжка приводящих лёжа с согнутой ногой',
  'side lying groin stretch': 'Растяжка паха лёжа на боку',
  'intermediate groin stretch': 'Растяжка паха (средний уровень)',
  'groin and back stretch': 'Растяжка паха и спины',
  'adductor/groin': 'Приводящие мышцы/пах (растяжка)',
  'adductor': 'Приводящие мышцы (растяжка)',
  'thigh adductor': 'Приведение бёдер в тренажёре',
  'thigh abductor': 'Отведение бёдер в тренажёре',
  'cable hip adduction': 'Приведение бедра на блоке',
  'band hip adductions': 'Приведение бедра с лентой',
  'hip extension with bands': 'Разгибание бедра с лентой',
  'hip flexion with band': 'Сгибание бедра с лентой',
  'hip lift with band': 'Подъём таза с лентой',
  'hip circles (prone)': 'Круги бёдрами в упоре лёжа',
  'standing hip circles': 'Круги тазом стоя',
  'shoulder circles': 'Круги плечами',
  'elbow circles': 'Круги локтями',
  'wrist circles': 'Круги запястьями',
  'ankle circles': 'Круги голеностопом',
  'kneeling arm drill': 'Дрилл для рук на коленях',
  'kneeling forearm stretch': 'Растяжка предплечий на коленях',
  'peroneals stretch': 'Растяжка малоберцовых мышц',
  'peroneals-smr': 'Малоберцовые мышцы (МФР)',
  'posterior tibialis stretch': 'Растяжка задней большеберцовой мышцы',
  'anterior tibialis-smr': 'Передняя большеберцовая мышца (МФР)',
  'calf stretch elbows against wall': 'Растяжка икр у стены (упор локтями)',
  'calf stretch hands against wall': 'Растяжка икр у стены (упор руками)',
  'standing gastrocnemius calf stretch': 'Растяжка икроножной мышцы стоя',
  'standing soleus and achilles stretch':
    'Растяжка камбаловидной мышцы и ахилла стоя',
  'seated calf stretch': 'Растяжка икр сидя',
  'calves-smr': 'Икры (МФР)',
  'foot-smr': 'Стопа (МФР)',
  'latissimus dorsi-smr': 'Широчайшие мышцы спины (МФР)',
  'hamstring-smr': 'Бицепс бедра (МФР)',
  'quadriceps-smr': 'Квадрицепсы (МФР)',
  'lower back-smr': 'Поясница (МФР)',
  'rhomboids-smr': 'Ромбовидные мышцы (МФР)',
  'brachialis-smr': 'Брахиалис (МФР)',
  'lower back curl': 'Прогиб в пояснице',
  'upper back-leg grab': 'Растяжка спины и ног (хват за ноги)',
  'upper back stretch': 'Растяжка верха спины',
  'middle back stretch': 'Растяжка середины спины',
  'dynamic back stretch': 'Динамическая растяжка спины',
  'dynamic chest stretch': 'Динамическая растяжка груди',
  'chair leg extended stretch': 'Растяжка ног на стуле',
  'chair lower back stretch': 'Растяжка поясницы на стуле',
  'chair upper body stretch': 'Растяжка верха тела на стуле',
  'dancer\'s stretch': 'Растяжка танцора',
  'runner\'s stretch': 'Растяжка бегуна',
  'downward facing balance': 'Баланс «собака мордой вниз»',
  'round the world shoulder stretch': 'Круговая растяжка плеч',
  'overhead stretch': 'Растяжка с поднятыми руками',
  'seated overhead stretch': 'Растяжка с поднятыми руками сидя',
  'side-lying floor stretch': 'Растяжка лёжа на боку',
  'upward stretch': 'Растяжка вверх',
};

export const OVERRIDES_PART6 = {
  // --- точечные исправления после прогона черновика ---
  'air bike': 'Айр-байк (воздушный велотренажёр)',
  'band pull apart': 'Разведение ленты-эспандера в стороны',
  'barbell guillotine bench press': 'Жим штанги лёжа «гильотина»',
  'barbell step ups': 'Зашагивания на тумбу со штангой',
  'bench press - powerlifting': 'Жим лёжа (пауэрлифтинг)',
  'bradford/rocky presses': 'Жимы Брэдфорда',
  'rocky pull-ups/pulldowns': 'Подтягивания/тяги «Рокки»',
  'butterfly': '«Бабочка» (сведение в тренажёре)',
  'cable iron cross': '«Железный крест» на блоке',
  'iron cross': '«Железный крест»',
  'iron crosses (stretch)': 'Растяжка «железный крест»',
  'cable judo flip': '«Бросок дзюдо» на блоке',
  'circus bell': 'Цирковой колокол (circus bell)',
  'clock push-up': 'Отжимания «циферблат»',
  'close-grip ez-bar curl with band':
    'Сгибания с EZ-грифом узким хватом с эспандером',
  'close-grip ez-bar press': 'Жим с EZ-грифом узким хватом',
  'close-grip ez bar curl': 'Сгибания с EZ-грифом узким хватом',
  'ez-bar curl': 'Сгибания рук с EZ-грифом',
  'ez-bar skullcrusher': 'Французский жим с EZ-грифом',
  'decline ez bar triceps extension':
    'Разгибания с EZ-грифом на скамье вниз головой',
  'cross body hammer curl': 'Молотковые сгибания поперёк корпуса',
  'cross over - with bands': 'Сведение в кроссовере с эспандером',
  'cuban press': 'Кубинский жим (вращения с гантелями)',
  'drop push': 'Отжимания с «дропом»',
  'handstand push-ups': 'Отжимания в стойке на руках',
  'hanging pike': 'Подъёмы ног «пайк» в висе',
  'heaving snatch balance': 'Рывковый баланс с подрывом',
  'high cable curls': 'Сгибания рук на верхнем блоке',
  'incline dumbbell bench with palms facing in':
    'Жим гантелей на наклонной скамье ладонями внутрь',
  'dumbbell lying pronation': 'Вращение гантели лёжа (пронация)',
  'dumbbell lying supination': 'Вращение гантели лёжа (супинация)',
  'dumbbell scaption': 'Подъёмы гантелей в плоскости лопаток (scaption)',
  'dumbbell seated one-leg calf raise':
    'Подъёмы на носки сидя на одной ноге с гантелью',
  'dumbbell one-arm shoulder press': 'Жим гантели над головой одной рукой',
  'dumbbell one-arm triceps extension':
    'Разгибание руки с гантелью на трицепс одной рукой',
  'dumbbell one-arm upright row': 'Тяга гантели к подбородку одной рукой',
  'dumbbell lying one-arm rear lateral raise':
    'Разведения на задние дельты лёжа одной рукой',
  'dumbbell step ups': 'Зашагивания на тумбу с гантелями',
  'step-up with knee raise': 'Зашагивание с подъёмом колена',
  'extended range one-arm kettlebell floor press':
    'Жим гири с пола одной рукой с удлинённой амплитудой',
  'front squats with two kettlebells': 'Приседания с двумя гирями у груди',
  'front two-dumbbell raise': 'Подъём двух гантелей перед собой',
  'hammer grip incline db bench press':
    'Жим гантелей на наклонной скамье молотковым хватом',
  'lying cambered barbell row': 'Тяга штанги с изогнутым грифом лёжа',
  'lying close-grip bar curl on high pulley':
    'Сгибания узким хватом на верхнем блоке лёжа',
  'lying close-grip barbell triceps extension behind the head':
    'Французский жим узким хватом из-за головы лёжа',
  'lying close-grip barbell triceps press to chin':
    'Жим на трицепс узким хватом к подбородку лёжа',
  'lying crossover': 'Сведения лёжа на задние дельты',
  'lying machine squat': 'Приседания в тренажёре лёжа (жим ногами)',
  'bodyweight mid row': 'Тяга к низкой опоре с собственным весом',
  'one-handed hang': 'Вис на одной руке',
  'overhead lat': 'Тяга верхнего блока из-за головы',
};
export const OVERRIDES_PART7 = {
  'palms-down dumbbell wrist curl over a bench':
    'Сгибание запястий с гантелями ладонями вниз на скамье',
  'palms-down wrist curl over a bench':
    'Сгибание запястий со штангой ладонями вниз на скамье',
  'palms-up barbell wrist curl over a bench':
    'Сгибание запястий со штангой ладонями вверх на скамье',
  'palms-up dumbbell wrist curl over a bench':
    'Сгибание запястий с гантелями ладонями вверх на скамье',
  'seated one-arm dumbbell palms-down wrist curl':
    'Сгибание запястий с гантелью ладонями вниз одной рукой сидя',
  'seated one-arm dumbbell palms-up wrist curl':
    'Сгибание запястий с гантелью ладонями вверх одной рукой сидя',
  'seated dumbbell palms-down wrist curl':
    'Сгибание запястий с гантелями ладонями вниз сидя',
  'seated dumbbell palms-up wrist curl':
    'Сгибание запястий с гантелями ладонями вверх сидя',
  'seated palm-up barbell wrist curl':
    'Сгибание запястий со штангой ладонями вверх сидя',
  'seated palms-down barbell wrist curl':
    'Сгибание запястий со штангой ладонями вниз сидя',
  'seated two-arm palms-up low-pulley wrist curl':
    'Сгибание запястий на нижнем блоке ладонями вверх сидя',
  'standing palms-up barbell behind the back wrist curl':
    'Сгибание запястий со штангой за спиной ладонями вверх стоя',
  'see-saw press (alternating side press)':
    'Жим «качели» (попеременный боковой жим)',
  'shotgun row': 'Тяга «дробовик» (shotgun row)',
  'side laterals to front raise':
    'Махи в стороны с переходом в подъём перед собой',
  'side to side box shuffle': 'Приставные шаги у тумбы',
  'single-arm linear jammer': 'Жим лендмайна одной рукой',
  'single-cone sprint drill': 'Спринт-дрилл с одним конусом',
  'single-leg high box squat': 'Приседания на высокий ящик на одной ноге',
  'single-leg stride jump': 'Прыжок с широким шагом на одной ноге',
  'sit squats': 'Приседания в сед',
  'skating': 'Коньковый шаг (skating)',
  'smith incline shoulder raise': 'Шраги в Смитте на наклонной скамье',
  'smith machine one-arm upright row': 'Тяга к подбородку в Смитте одной рукой',
  'smith machine overhead shoulder press': 'Жим над головой в Смитте',
  'smith machine stiff-legged deadlift':
    'Становая тяга на прямых ногах в Смитте',
  'smith single-leg split squat': 'Сплит-присед на одной ноге в Смитте',
  'speed band overhead triceps':
    'Быстрые разгибания на трицепс с лентой над головой',
  'speed box squat': 'Скоростные приседания на ящик',
  'speed squats': 'Скоростные приседания',
  'spinal stretch': 'Растяжка позвоночника',
  'split clean': 'Взятие на грудь в ножницы',
  'split snatch': 'Рывок в ножницы',
  'split squats': 'Сплит-присед (приседания в выпаде)',
  'split squat with dumbbells': 'Сплит-присед с гантелями',
  'squat with plate movers': {
    name: 'Приседания с дисками-«подложками» (plate movers)',
    status: 'needs_review',
    notes: 'Уточнить технику: диски под пятками или скользящие упоры',
  },
  'standing bradford press': 'Жим Брэдфорда стоя',
  'standing cable wood chop': '«Дровосек» на блоке стоя',
  'standing concentration curl': 'Концентрированные сгибания стоя',
  'standing low-pulley deltoid raise':
    'Махи в стороны на нижнем блоке стоя',
  'standing low-pulley one-arm triceps extension':
    'Разгибание руки на трицепс на нижнем блоке стоя',
  'standing one-arm cable curl': 'Сгибание руки на блоке одной рукой стоя',
  'standing one-arm dumbbell curl over incline bench':
    'Сгибание руки с гантелью через наклонную скамью стоя',
  'standing one-arm dumbbell triceps extension':
    'Разгибание руки с гантелью на трицепс одной рукой стоя',
  'standing overhead barbell triceps extension':
    'Разгибание рук со штангой над головой стоя',
  'standing palm-in one-arm dumbbell press':
    'Жим гантели одной рукой ладонью внутрь стоя',
  'standing palms-in dumbbell press': 'Жим гантелей ладонями внутрь стоя',
  'standing two-arm overhead throw': 'Бросок над головой двумя руками стоя',
  'trail running/walking': 'Бег/ходьба по пересечённой местности',
  'triceps overhead extension with rope':
    'Разгибания рук с канатом над головой (на трицепс)',
  'triceps pushdown - v-bar attachment': 'Разгибания на блоке с V-рукоятью',
  'v-bar pulldown': 'Тяга верхнего блока с V-рукоятью',
  'v-bar pullup': 'Подтягивания с V-рукоятью (нейтральным хватом)',
  'wide stance barbell squat': 'Приседания со штангой широкой постановкой',
  'wide stance stiff legs': 'Становая на прямых ногах, широкая постановка',
  'wind sprints': 'Рваные спринты',
  'zottman curl': 'Сгибания Зоттмана',
  'zottman preacher curl': 'Сгибания Зоттмана на скамье Скотта',
  'lateral cone hops': 'Прыжки через конусы в сторону',
  'front cone hops (or hurdle hops)':
    'Прыжки через конусы вперёд (или барьеры)',
  'single cone sprint drill': 'Спринт-дрилл с одним конусом',
  'step mill': 'Степ-миллер (лестница)',
  'carioca quick step': 'Кариока с быстрыми шагами',
  'chest push from 3 point stance': 'Толчок от груди из трёхточечного старта',
  'chest push with run release': 'Толчок от груди с разбегом',
  'knee tuck jump': 'Прыжок с подтягиванием коленей',
  'linear 3-part start technique': 'Линейная техника старта (3 части)',
  'linear acceleration wall drill': 'Дрилл ускорения у стены',
  'lunge pass through': 'Выпады с передачей снаряда (pass through)',
  'monster walk': '«Походка монстра» (шаги с резинкой)',
  'natural glute ham raise': 'Глют-хэм райз (обратное разгибание, без тренажёра)',
  'one handed hang': 'Вис на одной руке',
  'overhead cable curl': 'Сгибание рук на блоке над головой',
  'overhead triceps': 'Разгибания на трицепс над головой',
  'power partials': 'Частичные подъёмы в стороны (power partials)',
  'pyramid': '«Пирамида» (прыжковая серия)',
  'recumbent bike': 'Горизонтальный велотренажёр',
  'return push from stance': 'Толчок с возвратом в стойку',
  'reverse barbell preacher curls': 'Обратные сгибания со штангой на скамье Скотта',
  'scapular pull-up': 'Подтягивания с активацией лопаток (scapular pull-up)',
  'glute ham raise': 'Глют-хэм райз (обратное разгибание)',
  'floor glute-ham raise': 'Глют-хэм райз с пола',
  'spell caster': 'Поворотные махи (spell caster)',
  'spellcaster': 'Поворотные махи (spell caster)',
};

export const OVERRIDES_PART8 = {
  '3/4 sit-up': 'Сит-ап 3/4',
  'alternating deltoid raise': 'Махи на дельты попеременно',
  'alternate incline dumbbell curl':
    'Попеременные сгибания гантелей на наклонной скамье',
  'ankle on the knee': 'Голеностоп на колене (растяжка)',
  'balance board': 'Балансировочная платформа',
  'ball leg curl': 'Сгибание ног на фитболе',
  'band assisted pull-up': 'Подтягивания с помощью эспандера',
  'band skull crusher': 'Французский жим с эспандером',
  'barbell full squat': 'Приседания со штангой (глубокие)',
  'barbell glute bridge': 'Ягодичный мост со штангой',
  'barbell hack squat': 'Гакк-приседания со штангой за спиной',
  'barbell hip thrust': 'Ягодичный мост со штангой (hip thrust)',
  'barbell incline bench press - medium grip':
    'Жим штанги на наклонной скамье средним хватом',
  'barbell incline shoulder raise': 'Шраги со штангой на наклонной скамье',
  'barbell lunge': 'Выпады со штангой',
  'barbell rear delt row': 'Тяга штанги на задние дельты',
  'barbell seated calf raise': 'Подъёмы на носки сидя со штангой',
  'barbell shrug': 'Шраги со штангой',
  'barbell shrug behind the back': 'Шраги со штангой за спиной',
  'barbell side bend': 'Наклоны в сторону со штангой',
  'barbell side split squat': 'Сплит-присед в стороны со штангой',
  'barbell squat to a bench': 'Приседания со штангой до скамьи',
  'barbell walking lunge': 'Шагающие выпады со штангой',
  'bench dips': 'Обратные отжимания от скамьи',
  'bench jump': 'Прыжок на скамью',
  'bench sprint': 'Быстрые зашагивания на скамью (bench sprint)',
  'bent over dumbbell rear delt raise with head on bench':
    'Разведения на задние дельты с гантелями в наклоне, голова на скамье',
  'dumbbell incline row': 'Тяга гантели на наклонной скамье',
  'dumbbell prone incline curl':
    'Сгибания гантелей лёжа на животе на наклонной скамье',
  'dumbbell rear lunge': 'Выпады назад с гантелями',
  'dumbbell seated box jump': 'Прыжок на тумбу из седа с гантелями',
  'dumbbell shrug': 'Шраги с гантелями',
  'dumbbell side bend': 'Наклоны в сторону с гантелью',
  'dumbbell squat to a bench': 'Приседания с гантелями до скамью',
  'dumbbell tricep extension -pronated grip':
    'Разгибание руки с гантелью на трицепс пронированным хватом',
  'elevated back lunge': 'Выпады назад с возвышения',
  'elliptical trainer': 'Эллиптический тренажёр',
  'exercise ball pull-in': 'Подтягивания коленей к груди на фитболе',
  'external rotation with cable': 'Внешняя ротация на блоке',
  'fast skipping': 'Быстрые подскоки',
  'flat bench cable flyes': 'Разведения на блоке на горизонтальной скамье',
  'flat bench lying leg raise': 'Подъёмы ног лёжа на горизонтальной скамье',
  'flexor incline dumbbell curls':
    'Сгибания гантелей на наклонной скамье (акцент на сгибатели)',
  'forward drag with press': 'Тяга саней с жимом',
  'freehand jump squat': 'Прыжковые приседания без снаряда',
  'frog hops': 'Лягушачьи прыжки',
  'frog sit-ups': 'Сит-апы «лягушка»',
  'front barbell squat': 'Приседания со штангой на груди',
  'front barbell squat to a bench': 'Приседания со штангой на груди до скамьи',
  'front box jump': 'Прыжок на тумбу вперёд',
  'front cable raise': 'Подъём перед собой на блоке',
  'front dumbbell raise': 'Подъём гантелей перед собой',
  'front incline dumbbell raise':
    'Подъём гантелей перед собой на наклонной скамье',
  'front leg raises': 'Махи ногой вперёд',
  'front plate raise': 'Подъём диска перед собой',
  'front squat (clean grip)':
    'Приседания со штангой на груди (хват для взятия)',
  'glute kickback': 'Отведение ноги назад (ягодичный кикбэк)',
  'hang clean - below the knees': 'Взятие на грудь с виса ниже коленей',
  'hang snatch - below knees': 'Рывок с виса ниже коленей',
  'hanging leg raise': 'Подъёмы ног в висе',
  'lying high bench barbell curl': 'Сгибания со штангой лёжа на высокой скамье',
  'lying leg curls': 'Сгибания ног лёжа',
  'lying supine dumbbell curl': 'Сгибания гантелей лёжа на спине',
  'lying t-bar row': 'Тяга Т-грифа лёжа',
  'machine shoulder (military) press': 'Армейский жим в тренажёре',
  'middle back shrug': 'Шраги с акцентом на середину спины',
  'mixed grip chin': 'Подтягивания разнохватом',
  'narrow stance hack squats': 'Гакк-приседания узкой постановкой',
  'narrow stance leg press': 'Жим ногами узкой постановкой',
  'narrow stance squats': 'Приседания узкой постановкой',
  'oblique crunches': 'Боковые скручивания (на косые мышцы)',
  'one-arm flat bench dumbbell flye':
    'Разведение гантели лёжа на горизонтальной скамье одной рукой',
  'one-arm high-pulley cable side bends':
    'Наклоны в сторону на верхнем блоке одной рукой',
  'one arm dumbbell preacher curl':
    'Сгибания с гантелью на скамье Скотта одной рукой',
  'one arm pronated dumbbell triceps extension':
    'Разгибание руки с гантелью на трицепс пронированным хватом одной рукой',
  'one arm supinated dumbbell triceps extension':
    'Разгибание руки с гантелью на трицепс супинированным хватом одной рукой',
  'one leg barbell squat': 'Приседания на одной ноге со штангой (пистолетик)',
  'one-legged cable kickback':
    'Отведение ноги назад на блоке на одной ноге (кикбэк)',
  'bent over barbell row': 'Тяга штанги в наклоне',
  'bent over one-arm long bar row': 'Тяга длинного грифа в наклоне одной рукой',
  'bent over two-arm long bar row': 'Тяга длинного грифа в наклоне двумя руками',
  'bent over two-dumbbell row': 'Тяга двух гантелей в наклоне',
  'bent over two-dumbbell row with palms in':
    'Тяга двух гантелей в наклоне ладонями внутрь',
  'cable incline pushdown': 'Разгибания на трицепс на блоке (в наклоне)',
  'one-arm long bar row': 'Тяга длинного грифа одной рукой',
  'squats - with bands': 'Приседания с эспандером (без штанги)',
  'bicycling, stationary': 'Велотренажёр',
  'bodyweight flyes': 'Разведения с собственным весом',
  'bodyweight squat': 'Приседания с собственным весом',
  'bodyweight walking lunge': 'Шагающие выпады с собственным весом',
  'box skip': 'Скип на тумбу',
  'box squat with bands': 'Приседания на ящик с эспандером',
  'box squat with chains': 'Приседания на ящик с цепями',
  'cable deadlifts': 'Становая тяга на нижнем блоке',
  'cable hammer curls - rope attachment':
    'Молотковые сгибания на блоке с канатной рукоятью',
  'cable incline triceps extension':
    'Разгибание рук на трицепс на блоке на наклонной скамье',
  'cable internal rotation': 'Внутренняя ротация на блоке',
  'cable lying triceps extension': 'Разгибание рук на трицепс на блоке лёжа',
  'cable one arm tricep extension':
    'Разгибание руки на трицепс на блоке одной рукой',
  'cable preacher curl': 'Сгибания на скамье Скотта на блоке',
  'cable rear delt fly': 'Разведения на задние дельты на блоке',
  'cable rope overhead triceps extension':
    'Разгибание рук с канатом над головой на трицепс',
  'cable rope rear-delt rows': 'Тяга на блоке с канатом на задние дельты',
  'cable seated lateral raise': 'Разведения в стороны на блоке сидя',
  'cable shrugs': 'Шраги на блоке',
  'decline dumbbell flyes': 'Разведения с гантелями на скамье вниз головой',
  'decline dumbbell triceps extension':
    'Разгибание рук с гантелью на трицепс на скамье вниз головой',
  'decline smith press': 'Жим в Смитте на скамье вниз головой',
  'depth jump leap': 'Прыжок в глубину с выпрыгиванием',
  'dip machine': 'Тренажёр для отжиманий на брусьях',
  'dips - chest version': 'Отжимания на брусьях (акцент на грудь)',
  'dips - triceps version': 'Отжимания на брусьях (акцент на трицепс)',
  'drag curl': 'Сгибания с прижатием к корпусу (drag curl)',
  'dumbbell alternate bicep curl': 'Попеременные сгибания гантелей на бицепс',
  'dumbbell clean': 'Взятие на грудь с гантелями',
  'dumbbell flyes': 'Разведения с гантелями',
  'dumbbell incline shoulder raise': 'Шраги с гантелями на наклонной скамье',
  'dumbbell lunges': 'Выпады с гантелями',
  'dumbbell lying rear lateral raise':
    'Разведения на задние дельты с гантелями лёжа',
  'hyperextensions (back extensions)': 'Гиперэкстензия (разгибание спины)',
  'hyperextensions with no hyperextension bench':
    'Гиперэкстензия без специальной скамьи',
  'incline barbell triceps extension':
    'Разгибание рук со штангой на трицепс на наклонной скамье',
  'incline bench pull': 'Тяга лёжа на наклонной скамье',
  'incline dumbbell flyes': 'Разведения с гантелями на наклонной скамье',
  'incline dumbbell flyes - with a twist':
    'Разведения с гантелями на наклонной скамье с поворотом',
  'incline inner biceps curl':
    'Сгибания на бицепс (внутренняя головка) на наклонной скамье',
  'incline push-up depth jump': 'Прыжок в глубину из отжиманий на возвышении',
  'incline push-up medium': 'Отжимания на возвышении (средняя высота)',
  'incline push-up reverse grip': 'Отжимания на возвышении обратным хватом',
  'incline push-up wide': 'Отжимания на возвышении широким хватом',
  'inverted row with straps': 'Австралийские подтягивания на петлях (ремнях)',
  'kneeling cable triceps extension':
    'Разгибание рук на трицепс на блоке с колен',
  'kneeling single-arm high pulley row':
    'Тяга верхнего блока с колен одной рукой',
  "landmine 180's": 'Повороты с лендмайном на 180°',
  'lateral box jump': 'Прыжок на тумбу в сторону',
  'leg extensions': 'Разгибание ног',
  'leg lift': 'Подъёмы ног',
  'leverage decline chest press':
    'Жим от груди в рычажном тренажёре (вниз головой)',
  'leverage high row': 'Тяга в рычажном тренажёре (верхний блок)',
  'leverage incline chest press':
    'Жим от груди в рычажном тренажёре (наклонная)',
  'leverage iso row': 'Рычажная тяга (iso row)',
  'low cable crossover': 'Сведение в кроссовере на нижнем блоке',
  'low pulley row to neck': 'Тяга нижнего блока к шее',
  'lunge sprint': 'Выпады-спринт (прыжковые)',
  'clean deadlift': 'Становая тяга в стойке взятия',
  'close-grip front lat pulldown': 'Тяга верхнего блока к груди узким хватом',
  'close-grip push-up off of a dumbbell':
    'Отжимания узким хватом с опорой на гантель',
  'close-grip standing barbell curl': 'Сгибания со штангой узким хватом стоя',
  'crossover reverse lunge': 'Обратные выпады с перекрёстом',
  'kipping muscle up': 'Выход силой с киппингом',
  'kettlebell halo with overhead extension':
    '«Хало» с гирей и разгибанием над головой',
};

export const OVERRIDES = {
  ...OVERRIDES_PART1,
  ...OVERRIDES_PART2,
  ...OVERRIDES_PART3,
  ...OVERRIDES_PART4,
  ...OVERRIDES_PART5,
  ...OVERRIDES_PART6,
  ...OVERRIDES_PART7,
  ...OVERRIDES_PART8,
};







