// Фразы: многословные шаблоны. Применяются до одиночных слов,
// отсортированы по количеству слов (длинные — первыми).
// Ключи в нижнем регистре; дефис/пробел взаимозаменяемы при сопоставлении.
export const PHRASES_PART1 = {
  // --- жимы ---
  'barbell bench press': 'жим штанги лёжа',
  'dumbbell bench press': 'жим гантелей лёжа',
  'incline bench press': 'жим штанги на наклонной скамье',
  'decline bench press': 'жим штанги на скамье вниз головой',
  'incline dumbbell bench press': 'жим гантелей на наклонной скамье',
  'decline dumbbell bench press': 'жим гантелей на скамье вниз головой',
  'bench press': 'жим лёжа',
  'bench press with chains': 'жим лёжа с цепями',
  'bench press with bands': 'жим лёжа с эспандером',
  'bench press with chains': 'жим лёжа с цепями',
  'close-grip bench press': 'жим лёжа узким хватом',
  'wide-grip bench press': 'жим лёжа широким хватом',
  'close-grip barbell bench press': 'жим штанги лёжа узким хватом',
  'wide-grip barbell bench press': 'жим штанги лёжа широким хватом',
  'close-grip dumbbell press': 'жим гантелей узким хватом',
  'dumbbell press': 'жим гантелей',
  'dumbbell shoulder press': 'жим гантелей над головой',
  'barbell shoulder press': 'жим штанги над головой',
  'cable shoulder press': 'жим от плеч на блоке',
  'seated cable shoulder press': 'жим от плеч на блоке сидя',
  'shoulder press': 'жим над головой',
  'military press': 'армейский жим',
  'machine shoulder press': 'жим над головой в тренажёре',
  'machine shoulder (military) press': 'армейский жим в тренажёре',
  'arnold dumbbell press': 'жим Арнольда с гантелями',
  'chest press': 'жим от груди',
  'leg press': 'жим ногами',
  'calf press': 'жим носками (пресс икр)',
  'push press': 'швунг',
  'floor press': 'жим с пола',
  'dumbbell floor press': 'жим гантелей с пола',
  'board press': 'жим с досок',
  'pin presses': 'жим со штырей в раме',
  'chain press': 'жим с цепями',
  'svend press': 'жим Свенда',
  'tate press': 'жим Тейта',
  'jm press': 'жим JM',
  'bent press': 'жим в наклоне (bent press)',
  'pallof press': 'жим Паллофа',
  'calf press on the leg press machine': 'пресс икр в тренажёре жима ногами',
  'machine bench press': 'жим лёжа в тренажёре',

  // --- приседания / тяги ---
  'barbell squat': 'приседания со штангой',
  'dumbbell squat': 'приседания с гантелями',
  'front squat': 'приседания со штангой на груди',
  'overhead squat': 'приседания со штангой над головой',
  'hack squat': 'гакк-приседания',
  'box squat': 'приседания на ящик',
  'split squat': 'сплит-присед (приседания в выпаде)',
  'sissy squat': 'сисси-приседания',
  'pistol squat': 'приседания на одной ноге (пистолетик)',
  'goblet squat': 'приседания гоблет (с гирей у груди)',
  'squat to a bench': 'приседания до скамьи',
  'squat with bands': 'приседания с эспандером',
  'squat with chains': 'приседания с цепями',
  'zercher squats': 'приседания Зерчера',
  'jefferson squats': 'приседания Джефферсона',
  'plie dumbbell squat': 'приседания плие с гантелью',
  'barbell deadlift': 'становая тяга со штангой',
  'sumo deadlift': 'становая тяга сумо',
  'romanian deadlift': 'румынская тяга',
  'deficit deadlift': 'становая тяга с дефицита',
  'deadlift with bands': 'становая тяга с эспандером',
  'deadlift with chains': 'становая тяга с цепями',
  'stiff-legged barbell deadlift': 'становая тяга на прямых ногах со штангой',
  'stiff-legged dumbbell deadlift': 'становая тяга на прямых ногах с гантелями',
  'trap bar deadlift': 'становая тяга с трэп-грифом',
  'rack pull': 'тяга в силовой раме (rack pull)',
  'barbell row': 'тяга штанги в наклоне',
  'bent over barbell row': 'тяга штанги в наклоне',
  'dumbbell row': 'тяга гантели в наклоне',
  'one-arm dumbbell row': 'тяга гантели одной рукой в наклоне',
  'dumbbell incline row': 'тяга гантели на наклонной скамье',
  'inverted row': 'австралийские подтягивания (тяга в висе лёжа)',
  'upright row': 'тяга к подбородку',
  'face pull': 'тяга к лицу',
  'seated cable rows': 'тяга нижнего блока сидя',
  'elevated cable rows': 'тяга нижнего блока с упором',
  'lying t-bar row': 'тяга Т-грифа лёжа',
  't-bar row with handle': 'тяга Т-грифа с рукоятью',
  'long bar row': 'тяга длинного грифа в наклоне',
  'rear delt raise': 'разведения на задние дельты',
  'rear delt row': 'тяга на задние дельты',
  'delt raise': 'махи на дельты',
  'dumbbell raise': 'подъём гантелей в стороны',
  'cable row': 'тяга нижнего блока',
  'high pulley row': 'тяга верхнего блока',
  'pull through': 'тяга нижнего блока между ног',
};
export const PHRASES_PART2 = {
  // --- руки ---
  'barbell curl': 'сгибание рук со штангой',
  'dumbbell curl': 'сгибание рук с гантелями',
  'dumbbell bicep curl': 'сгибание рук с гантелями на бицепс',
  'bicep curl': 'сгибание рук на бицепс',
  'biceps curl': 'сгибание рук на бицепс',
  'hammer curls': 'молотковые сгибания',
  'hammer curl': 'молотковое сгибание',
  'preacher curl': 'сгибания на скамье Скотта',
  'preacher hammer dumbbell curl': 'молотковые сгибания на скамье Скотта',
  'concentration curls': 'концентрированные сгибания',
  'reverse curl': 'сгибания обратным хватом',
  'wrist curl': 'сгибание запястий',
  'wrist curl over a bench': 'сгибание запястий на скамье',
  'leg curl': 'сгибание ног',
  'cable curl': 'сгибание рук на блоке',
  'triceps extension': 'разгибание рук на трицепс',
  'tricep extension': 'разгибание рук на трицепс',
  'overhead triceps extension': 'разгибание рук над головой на трицепс',
  'skullcrusher': 'французский жим (скилл-крашер)',
  'skull crusher': 'французский жим (скилл-крашер)',
  'triceps pushdown': 'разгибания на блоке (пушдаун)',
  'kickback': 'кикбэк (разгибание руки в наклоне)',
  'triceps press': 'жим на трицепс',
  'tricep press': 'жим на трицепс',

  // --- брусья / отжимания / подтягивания / блок ---
  'parallel bar dip': 'отжимания на брусьях',
  'bench dip': 'обратные отжимания от скамьи',
  'ring dips': 'отжимания на кольцах',
  'pull-up': 'подтягивания',
  'pull up': 'подтягивания',
  'pull ups': 'подтягивания',
  'chin-up': 'подтягивания обратным хватом',
  'push-up': 'отжимания',
  'push up': 'отжимания',
  'pushups': 'отжимания',
  'push ups': 'отжимания',
  'incline push-up': 'отжимания с упором на возвышение',
  'decline push-up': 'отжимания с ногами на возвышении',
  'lat pulldown': 'тяга верхнего блока',
  'cable crossover': 'сведение в кроссовере',
  'cable crunch': 'скручивания на блоке',
  'cable chest press': 'жим от груди на блоке',
  'cable flye': 'разведения на блоке',
  'flyes': 'разведения',
  'cable lateral raise': 'разведения в стороны на блоке',
  'lateral raise': 'разведения в стороны',
  'front raise': 'подъём перед собой',
  'side bend': 'наклоны в сторону',
  'good morning': 'гуд морнинг (наклон со снарядом)',
  'reverse crunch': 'обратные скручивания',
  'leg raise': 'подъёмы ног',
  'leg raises': 'подъёмы ног',
  'knee raise': 'подъёмы коленей',
  'hip raise': 'подъёмы таза',
  'hip thrust': 'ягодичный мостик (hip thrust)',
  'glute bridge': 'ягодичный мост',
  'leg pull-in': 'подтягивания коленей к груди',
  'sit-up': 'сит-ап',
  'sit ups': 'сит-апы',
  'hyperextension': 'гиперэкстензия',
  'back extension': 'разгибание спины',
  'muscle up': 'выход силой',
  'pullover': 'пуловер',
  'calf raise': 'подъём на носки',
  'calf raises': 'подъёмы на носки',
  'calf stretch': 'растяжка икр',
  'quad stretch': 'растяжка квадрицепсов',
  'hamstring stretch': 'растяжка бицепса бедра',
  'chest stretch': 'растяжка груди',
  'shoulder stretch': 'растяжка плеч',
  'back stretch': 'растяжка спины',
  'groin stretch': 'растяжка паха',
  'knee circles': 'круги коленями',
  'arm circles': 'круги руками',
  'external rotation': 'внешняя ротация',
  'internal rotation': 'внутренняя ротация',
  'depth jump': 'прыжок в глубину',
  'box jump': 'прыжок на тумбу',
  'jump squat': 'прыжковые приседания',
  'medicine ball': 'медицинбол',
  'exercise ball': 'фитбол',
  'stability ball': 'фитбол',
  'chest pass': 'пас от груди',
  'chest push': 'толчок от груди',
  'overhead throw': 'бросок над головой',
  'scoop throw': 'бросок снизу',
  'with bands': 'с эспандером',
  'with band': 'с эспандером',
  'with chains': 'с цепями',
  'with a twist': 'с поворотом',
  'rope attachment': 'с канатной рукоятью',
  'v-bar attachment': 'с V-рукоятью',
  'behind the neck': 'из-за головы',
  'behind the back': 'за спиной',
  'against wall': 'у стены',
  'against a wall': 'у стены',
  'to a bench': 'до скамьи',
  'on the floor': 'на полу',
  'on an exercise ball': 'на фитболе',
  'on a stability ball': 'на фитболе',
  'from blocks': 'с плинтов',
  'on parallel bars': 'на брусьях',
  'smith machine': 'в тренажёре Смитта',
  'multiple response': 'многократный отклик',
  'single response': 'однократный отклик',
  'or hurdle hops': 'или прыжки через барьеры',
  'hurdle hops': 'прыжки через барьеры',
  'power clean': 'взятие на грудь без подседа',
  'hang clean': 'взятие на грудь с виса',
  'hang snatch': 'рывок с виса',
  'power snatch': 'рывок без подседа',
  'power jerk': 'толчок без подседа',
  'clean and jerk': 'толчок (взятие + толчок)',
  'clean and press': 'взятие на грудь и жим',
  'clean pull': 'тяга-подрыв (clean pull)',
  'clean shrug': 'шраги с подрывом',
  'snatch pull': 'тяга-подрыв в рывке',
  'snatch balance': 'рывковый баланс',
  'split jerk': 'толчок в ножницы',
  'squat jerk': 'толчок с подседом',
  'muscle snatch': 'силовой рывок (без подседа)',
  'from the hang position': 'с виса',
};

export const PHRASES_PART3 = {
  // --- хваты и рукоятки ---
  'close-grip': 'узким хватом',
  'wide-grip': 'широким хватом',
  'medium grip': 'средним хватом',
  'reverse grip': 'обратным хватом',
  'neutral grip': 'нейтральным хватом',
  'hammer grip': 'молотковым хватом',
  'pronated grip': 'пронированным хватом',
  'supinated grip': 'супинированным хватом',
  'palms-up': 'ладонями вверх',
  'palms-down': 'ладонями вниз',
  'palms-in': 'ладонями внутрь',
  'palm-in': 'ладонями внутрь',
  'palms facing in': 'ладонями внутрь',
  'palms up': 'ладонями вверх',
  'palms down': 'ладонями вниз',
  'stiff-legged': 'на прямых ногах',
  'stiff leg': 'на прямых ногах',
  'straight-arm': 'прямыми руками',
  'bent-arm': 'согнутыми руками',
  'bent-over': 'в наклоне',
  'one-arm': 'одной рукой',
  'two-arm': 'двумя руками',
  'one-legged': 'на одной ноге',
  'one-leg': 'на одной ноге',
  'single-leg': 'на одной ноге',
  'with dumbbells': 'с гантелями',
  'with two kettlebells': 'с двумя гирями',
  'with rope': 'с канатом',
  'with handle': 'с рукоятью',

  // --- блоки и тренажёры ---
  'low-pulley': 'нижнего блока',
  'high-pulley': 'верхнего блока',
  'low pulley': 'нижнего блока',
  'high pulley': 'верхнего блока',
  'low cable': 'на нижнем блоке',
  'high cable': 'на верхнем блоке',
  'one pulley': '',
  'cable pulley': 'блока',
  'ez-bar': 'с EZ-грифом',
  'ez bar': 'с EZ-грифом',
  'v-bar': 'с V-рукоятью',
  't-bar': 'с Т-грифом',
  'trap bar': 'с трэп-грифом',

  // --- уточнения частых комбинаций ---
  'upright barbell row': 'тяга штанги к подбородку',
  'upright cable row': 'тяга нижнего блока к подбородку',
  'upright row': 'тяга к подбородку',
  'step ups': 'зашагивания',
  'step up': 'зашагивание',
  'sit-ups': 'сит-апы',
  'preacher curls': 'сгибания на скамье Скотта',
  'good mornings': 'гуд морнинг (наклон со снарядом)',
  'pull-ups': 'подтягивания',
  'push-ups': 'отжимания',
  'side lateral': 'разведения в стороны',
  'pull apart': 'разведение в стороны (pull apart)',
  'wood chop': '«дровосек» (рубка)',
  'guillotine bench press': 'жим лёжа «гильотина»',
  'ez-bar curl': 'сгибание рук с EZ-грифом',
  'ez-bar skullcrusher': 'французский жим с EZ-грифом',
  'rear-delt': 'на задние дельты',
  'iso row': 'рычажная тяга (iso row)',
  'cross over': 'сведение в кроссовере',
  'crossover': 'кроссовер',
  'scaption': 'в плоскости лопаток (scaption)',
  'russian twists': 'русские скручивания',
  'narrow stance': 'узкой постановкой ног',
  'wide stance': 'широкой постановкой ног',
  'legged': '',
};

export const PHRASES = { ...PHRASES_PART1, ...PHRASES_PART2, ...PHRASES_PART3 };

