// Словарь одиночных слов (fallback после фраз). Ключи в нижнем регистре.
// Пустая строка означает «слово опускается в переводе».
export const WORDS_PART1 = {
  // --- стоп-слова ---
  the: '', a: '', an: '', your: '', of: '', or: '', it: '', no: '',
  with: 'с', and: 'и', on: 'на', in: 'в', into: 'в',
  to: 'к', from: 'с', off: 'со', over: 'над', under: 'под', above: 'над',
  below: 'под', behind: 'за', between: 'между', against: 'у', around: 'вокруг',
  up: 'вверх', down: 'вниз', out: '', at: '', all: '', is: '', s: '', t: '',
  for: '', by: '',

  // --- положение тела / позиция ---
  standing: 'стоя', seated: 'сидя', sitting: 'сидя', lying: 'лёжа',
  kneeling: 'на коленях', prone: 'лёжа на животе', supine: 'лёжа на спине',
  suspended: 'в петлях', elevated: 'на возвышении', hanging: 'в висе',
  bent: 'согнутыми', straight: 'прямыми', flat: 'горизонтальный',
  incline: 'на наклонной скамье', decline: 'на скамье вниз головой',
  inverted: 'обратный', weighted: 'с весом', bodyweight: 'с собственным весом',
  freehand: 'без снаряда', isometric: 'изометрический', dynamic: 'динамический',
  advanced: 'продвинутый', intermediate: 'средний уровень',
  single: 'один', double: 'двойной', multiple: 'многократный',
  assisted: 'с помощью', full: 'полный', half: 'полу-',
  wide: 'широкий', close: 'узкий', narrow: 'узкий', medium: 'средний',
  reverse: 'обратный', alternate: 'попеременный', alternating: 'попеременный',
  external: 'внешняя', internal: 'внутренняя', neutral: 'нейтральный',
  pronated: 'пронированный', supinated: 'супинированный',
  mixed: 'смешанный', open: 'открытой', stiff: 'прямыми', legs: 'ноги',
  one: 'одной', two: 'двумя', low: 'нижнего', high: 'верхнего',
  upright: 'вертикальный', stance: 'постановка ног', step: 'шаг',
  legged: 'ногах', split: 'сплит', db: 'гантели', pike: '«пайк»',
  spinal: 'позвоночника', speed: 'скоростные', shuffle: 'приставные шаги',
  cone: 'конус', handstand: 'в стойке на руках', pronation: 'пронация',
  supination: 'супинация', laterals: 'махи в стороны', wood: 'дров',
  chop: 'рубка', apart: 'в стороны', rope_: '', judo: 'дзюдо',
  butterfly: '«бабочка»', circus: 'цирковая', bell: 'колокол',
  clock: '«циферблат»', cross: 'крест', cuban: 'кубинский',
  drop: 'дроп', heaving: 'с подрывом', bradford: 'Брэдфорда',
  rocky: '«Рокки»', concentration: 'концентрированные',
  guillotine: '«гильотина»', powerlifting: 'пауэрлифтинг', sit: 'сед',
  shotgun: '«дробовик»', skater: 'коньковый', skating: 'коньковый шаг',
  mill: '', straddle: 'складка', zottman: 'Зоттмана', trail: 'пересечённая',
  jammer: '«джаммер»', movers: 'подложками', extended_: '',
  front: 'передний', rear: 'задний', back: 'спина', side: 'боковой',
  sides: 'стороны', middle: 'середина', upper: 'верх', lower: 'низ',
  inner: 'внутренний', mid: 'середина',
  backward: 'назад', forward: 'вперёд', diagonal: 'диагональный',
  lateral: 'боковой', vertical: 'вертикальный', linear: 'линейный',
  quick: 'быстрый', fast: 'быстрый', heavy: 'тяжёлый',
  long: 'длинный', extended: 'расширенный', depth: 'глубина',
};
export const WORDS_PART2 = {
  // --- инвентарь ---
  barbell: 'штанга', dumbbell: 'гантель', dumbbells: 'гантели',
  kettlebell: 'гиря', kettlebells: 'гири', cable: 'на блоке',
  pulley: 'блок', machine: 'тренажёр', leverage: 'рычажный тренажёр',
  smith: 'Смитта', bench: 'скамья', box: 'тумба', bar: 'гриф',
  ez: 'EZ-гриф', band: 'эспандер', bands: 'эспандер',
  medicine: 'медицинбол', ball: 'мяч', plate: 'диск', plates: 'диски',
  rope: 'канат', ropes: 'канаты', chain: 'цепь', chains: 'цепи',
  sled: 'сани', wall: 'у стены', floor: 'на полу', chair: 'стул',
  board: 'доска', ring: 'кольца', rings: 'кольца', log: 'лог',
  axle: 'ось', yoke: 'йок', tire: 'шина', bag: 'мешок',
  sandbag: 'мешок с песком', keg: 'бочка', stone: 'камень',
  stones: 'камни', sledgehammer: 'кувалда', straps: 'ремни',
  harness: 'упряжь', handle: 'рукоять', trainer: 'тренажёр',
  treadmill: 'беговая дорожка', bike: 'велотренажёр',
  bicycling: 'велосипед', stationary: 'стационарный', elliptical: 'эллипсоид',
  rowing: 'гребля', stairmaster: 'степпер', stairs: 'лестница',
  roller: 'ролик', platform: 'платформа', exercise: 'упражнение',
  physioball: 'фитбол', bosu: 'босу', rickshaw: 'рикша', landmine: 'лендмайн',
  pins: 'штыри', pin: 'штырь', towel: 'полотенце', iron: 'железный',

  // --- движения ---
  press: 'жим', presses: 'жимы', push: 'толчок', pushup: 'отжимание',
  pushups: 'отжимания', squat: 'приседание', squats: 'приседания',
  deadlift: 'становая тяга', deadlifts: 'становые тяги', dead: 'становая',
  row: 'тяга', rows: 'тяги', curl: 'сгибание', curls: 'сгибания',
  raise: 'подъём', raises: 'подъёмы', lift: 'подъём',
  extension: 'разгибание', extensions: 'разгибания',
  pull: 'тяга', pulls: 'тяги', pulldown: 'тяга верхнего блока',
  pulldowns: 'тяги верхнего блока', dip: 'отжимание на брусьях',
  dips: 'отжимания на брусьях', lunge: 'выпад', lunges: 'выпады',
  crunch: 'скручивание', crunches: 'скручивания', 'sit-up': 'сит-ап',
  shrug: 'шраг', shrugs: 'шраги', flye: 'разведение', flyes: 'разведения',
  fly: 'разведение', pullover: 'пуловер', hyperextension: 'гиперэкстензия',
  hyperextensions: 'гиперэкстензии', clean: 'взятие на грудь',
  snatch: 'рывок', jerk: 'толчок', swing: 'махи', swings: 'махи',
  thruster: 'трастер', thrust: 'толчок', plank: 'планка', bridge: 'мост',
  bridges: 'мосты', kickback: 'кикбэк', pushdown: 'разгибания на блоке',
  crossover: 'кроссовер', hop: 'прыжок', hops: 'прыжки', jump: 'прыжок',
  jumping: 'прыжки', bound: 'многоскок', leap: 'прыжок', sprint: 'спринт',
  sprints: 'спринты', walk: 'ходьба', walking: 'ходьба', carry: 'переноска',
  run: 'бег', running: 'бег', jogging: 'бег трусцой', skip: 'подскок',
  skipping: 'подскоки', climb: 'лазание', crawl: 'ползание', drag: 'тяга',
  drags: 'тяги', pullup: 'подтягивание', pullups: 'подтягивания',
  chin: 'подтягивание', chins: 'подтягивания', throw: 'бросок',
  pass: 'передача', catch: 'ловля', slam: 'сброс', delivery: 'выполнение',
  stretch: 'растяжка', circles: 'круги', rotation: 'вращение',
  rotations: 'вращения', twist: 'повороты', twists: 'повороты',
  bend: 'наклон', bends: 'наклоны', tilt: 'наклон', flexion: 'сгибание',
  flexor: 'сгибатель', flexors: 'сгибатели', squeeze: 'сжатие',
  squeezes: 'сжатия', grip: 'хват', rollout: 'выкатывание',
  flip: 'переворот', wipers: '«дворники»', touchers: 'касания',
  touches: 'касания', vacuum: 'вакуум', hug: 'обнять', grab: 'хват',

  // --- части тела / мышцы ---
  arm: 'рукой', arms: 'руками', bicep: 'бицепс', biceps: 'бицепс',
  brachialis: 'брахиалис', tricep: 'трицепс', triceps: 'трицепс',
  forearm: 'предплечье', wrist: 'запястья', finger: 'палец',
  hand: 'рукой', hands: 'руками', chest: 'грудь', shoulder: 'плечо',
  shoulders: 'плечи', delt: 'дельта', deltoid: 'дельтовидная',
  lat: 'широчайшие', lats: 'широчайшие', neck: 'шея', ab: 'пресс',
  abs: 'пресс', oblique: 'косые мышцы', quad: 'квадрицепс',
  quadriceps: 'квадрицепсы', hamstring: 'бицепс бедра',
  ham: 'бицепс бедра', glute: 'ягодицы', calf: 'икры', calves: 'икры',
  gastrocnemius: 'икроножная', soleus: 'камбаловидная',
  achilles: 'ахилл', tibialis: 'большеберцовая', peroneals: 'малоберцовые',
  piriformis: 'грушевидная', rhomboids: 'ромбовидные', traps: 'трапеции',
  hip: 'бедро', hips: 'бёдра', groin: 'пах', adductor: 'приводящие',
  adduction: 'приведение', abductor: 'отводящие', leg: 'нога',
  thigh: 'бедро', knee: 'колено', knees: 'колени', ankle: 'голеностоп',
  foot: 'стопа', feet: 'ноги', heel: 'пятка', toe: 'носок', toes: 'носки',
  elbow: 'локоть', elbows: 'локти', torso: 'корпус', stomach: 'живот',
  pelvic: 'таз', butt: 'ягодицы', head: 'голова', body: 'тело',
  palm: 'ладонь', palms: 'ладони',

  // --- прочее ---
  power: 'силовой', olympic: 'олимпийский', plyo: 'плиометрический',
  morning: 'гуд морнинг', good: 'гуд', style: 'вариант', version: 'вариант',
  technique: 'техника', drill: 'дрилл', series: 'серия',
  progression: 'прогрессия', response: 'отклик', range: 'амплитуда',
  motion: 'движение', position: 'положение', resistance: 'сопротивление',
  manual: 'ручное', balance: 'баланс', world: 'мира',
  windmill: 'мельница', windmills: 'мельницы', seesaw: '«качели»',
  halo: 'хало', kipping: 'киппинг', muscle: 'мышцы', spider: 'паук',
  frog: 'лягушка', gorilla: 'горилла', donkey: 'ослик', sissy: 'сисси',
  plie: 'плие', pistol: 'пистолетик', goblet: 'гоблет', hack: 'гакк',
  sumo: 'сумо', romanian: 'румынская', deficit: 'дефицит',
  blocks: 'плинты', rack: 'рама', hang: 'вис',
};

export const WORDS = { ...WORDS_PART1, ...WORDS_PART2 };

